# Lifted from github.com/squint-cljs/cherry

name: Tests

on: [push, pull_request]

env:
  SECRET: testing
  TESTING: 1
  DATABASE_URL: sqlite://./tests.sqlite
  PORT: 8000
  TIMEOUT: 60

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # windows-latest
        version: [16, 18, 20]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.version }}

    - name: Prepare java
      uses: actions/setup-java@v4
      with:
        distribution: "adopt"
        java-version: 11

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.10.3.1040

    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('shadow-cljs.edn') }}
        # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
        # key: cljdeps-${{ hashFiles('project.clj') }}
        # key: cljdeps-${{ hashFiles('build.boot') }}
        restore-keys: cljdeps-

    - name: Install Node deps
      run: npm i

    # Main test suite

    - name: Run the tests
      run: npm run test

    - name: Run the e2e tests
      run: npm run test-e2e

   # Test suite with PostgreSQL as a db

    - name: Set up PostgreSQL
      run: |
        sudo apt update
        sudo apt install -y postgresql libpq-dev
        sudo service postgresql start
        sudo -u postgres createuser --superuser "$USER"
      if: runner.os == 'Linux'

    - name: Run the tests on Postgres
      run: npm run test-postgres
      if: runner.os == 'Linux'

    # npm init "create" script tests

    - name: Link local packages for create tests
      run: npm link

    - name: Create temporary directory for create tests
      run: mkdir test-create-scripts

    - name: Link fullstack create package for create tests
      run: cd create/sitefox-fullstack && npm link

    - name: Test npm create sitefox-fullstack
      working-directory: ./test-create-scripts
      run: |
        set -e
        # Use absolute path for npm create as we are in a different working dir
        npm create sitefox-fullstack test-fullstack-app --prefix ../
        cd test-fullstack-app
        npm install
        make watch &
        bgpid=$!
        echo "Server PID: $bgpid"
        # Use double quotes for bash -c to allow $bgpid expansion
        if timeout $TIMEOUT bash -c \
          "until echo > /dev/tcp/localhost/$PORT; do \
             echo -n '.'; \
             # Check if background process is still running
             kill -0 $bgpid 2>/dev/null || { echo 'Server died.'; exit 1; }; \
             sleep 1; \
           done 2>/dev/null"; then
          echo "-> CI saw server start successfully."
        else
          # Failure message updated slightly to reflect the new check
          echo "-> CI failed to see server."
          exit 1 # Exit with error if server fails to start
        fi
        echo "Attempting to kill processes after successful test..."
        pkill -f make || true
        pkill -f java || true
        pkill -f node || true
        sleep 2 # Give processes time to terminate gracefully
        # Verify port is free
        if lsof -i :$PORT; then
          echo "ERROR: Port $PORT still in use after kill attempts!"
          exit 1
        else
          echo "Port $PORT is free after kill attempts."
        fi

    - name: Link nbb create package for create tests
      run: cd create/sitefox-nbb && npm link

    - name: Test npm create sitefox-nbb
      working-directory: ./test-create-scripts
      run: |
        set -e
        # Use absolute path for npm create as we are in a different working dir
        npm create sitefox-nbb test-nbb-app --prefix ../
        cd test-nbb-app
        npm install
        echo "Checking port $PORT before starting nbb server..."
        lsof -i :$PORT || echo "Port $PORT is free before nbb serve"
        npm run serve &
        bgpid=$!
        echo "Server PID: $bgpid"
        # Use double quotes for bash -c to allow $bgpid expansion
        if timeout $TIMEOUT bash -c \
          "until echo > /dev/tcp/localhost/$PORT; do \
             echo -n '.'; \
             # Check if background process is still running
             kill -0 $bgpid 2>/dev/null || { echo 'Server died.'; exit 1; }; \
             sleep 1; \
           done 2>/dev/null"; then
          echo "-> CI saw server start successfully."
        else
          # Failure message updated slightly to reflect the new check
          echo "-> CI failed failed to see server."
          exit 1 # Exit with error if server fails to start
        fi
        pkill -f node || true
        sleep 2 # Give processes time to terminate gracefully
